# Available Options
# rpm (Fedora)
# deb (Debian Based: Ubuntu, Mint, PopOS, kali, etc...)
PKGType = "rpm"

# Place Where You Want Files To Be Downloaded
DownloadPath = "~/.cache/pkgfetch"

# Place Where You Want Your Packages's bin To Be Symlinked
# Make Sure This Path Is In `$PATH` (check with `echo $PATH`)
# Leave It Empty If You Don't Want Symlinks
SymlnkPath = "~/.local/bin"
