# Available Options
# fedora
# ubuntu
Distro: fedora

# Place Where You Want Files To Be Downloaded
DownloadPath: ~/Downloads

# Place Where You Want Your Packages's bin To Be Symlinked
# Make Sure This Path Is In `$PATH` (check with `echo $PATH`)
# Leave It Empty If You Don't Want Symlinks
SymlnkPath: ~/.local/bin
